name = "AI Puppy Lesson 1_Jav_June26 Copy"

[files]
"https://chrisrogers.pyscriptapps.com/cbr-libraries/latest/core/andrea_terminal.py" = "andrea_terminal.py"
"https://chrisrogers.pyscriptapps.com/cbr-libraries/latest/core/ampy.py" = "ampy.py"
"https://chrisrogers.pyscriptapps.com/cbr-libraries/latest/core/restapi.py" = "restapi.py"
"https://chrisrogers.pyscriptapps.com/cbr-libraries/latest/core/file_os.py" = "file_os.py"
"https://raw.githubusercontent.com/iliketocode2/AI-Puppy-UI/main/my_globals.py?token=GHSAT0AAAAAACTCAVUHEYYK7W524ZH2BLAYZURZQQQ" = "./my_globals.py"
"https://raw.githubusercontent.com/iliketocode2/AI-Puppy-UI/main/sensor_mod.py?token=GHSAT0AAAAAACTCAVUHN5VI2IR65P7YKCZYZURZR4Q" = "./sensor_mod.py"
"https://raw.githubusercontent.com/iliketocode2/AI-Puppy-UI/main/print_jav.py?token=GHSAT0AAAAAACTCAVUHY2QMOHROQI74ZTN2ZURZSGA" = "./print_jav.py"
"https://raw.githubusercontent.com/iliketocode2/AI-Puppy-UI/main/my_gif.py?token=GHSAT0AAAAAACTCAVUHG2CN4HRYT6UZMCZGZURZSOA" = "./my_gif.py"
"https://raw.githubusercontent.com/iliketocode2/AI-Puppy-UI/main/helper_mod.py?token=GHSAT0AAAAAACTCAVUG2GIJR47CGZD5N3M6ZURZSZQ" = "./helper_mod.py"



[js_modules.main]
"https://esm.run/micro-repl@0.5.0/serial" = "micro_repl"
